# Generated by Django 5.2.10 on 2026-01-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('sell', models.FloatField()),
                ('purchase', models.FloatField()),
                ('qty', models.IntegerField()),
                ('min_stock', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
    ]
